config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  resources :inventories

  resources :contracts

  resources :tickets do
    resources :comments
  end

  get 'dashboard' => 'dashboard#index', as: :dashboard

  get 'search' => 'search#index', as: :search

  get 'signup' => 'users#new'
  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  match "*path", to: "sessions#new", via: :all

end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  
  # scope :by_name, -> name { where(name: name) if status.present? }

  # Filter on inventories index.html
  def self.by_equipment(equipment)
    if equipment.present?
      where(equipment: equipment)
    else
      all
    end
  end

  # Filter on inventories index.html
  def self.by_status(status)
    if status.present?
      where(status: status)
    else
      all
    end
  end

end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :logged_in_user

  def new
		@inventory = Inventory.new
  end

  def create
    @inventory = Inventory.new(inventory_params)

    if @inventory.save
      flash[:success] = "Asset successfully created."
    	redirect_to @inventory
		else
			render 'new'
		end
  end

  def show
    @inventory = Inventory.find(params[:id])
  end

  def edit
    @inventory = Inventory.find(params[:id])
  end

  def update
    @inventory = Inventory.find(params[:id])

    if @inventory.update(inventory_params)
      redirect_to @inventory
    else
      render 'edit'
    end
  end

  def destroy
    @inventory = Inventory.find(params[:id])
    @inventory.destroy
    flash[:success] = "Asset successfuly deleted."
    redirect_to inventories_path
  end

	def index
    @inventory = Inventory.by_equipment(params[:equipment]).by_status(params[:status]).paginate(page: params[:page], per_page: 15)
	end

  private
    def inventory_params
      params.require(:inventory).permit(
      :name,
      :serial,
      :barcode,
      :model,
      :equipment,
      :purchasedate,
      :comments,
      :owner,
      :status,
      :operating_system,
      :department,
      :ip_address,
      :service_tag
      )
    end
  end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/edit.html.erb
<div class="row">
  <div class="col-sm-12">

    <h1>Edit Asset:</h1>

      <%= render 'layouts/assetform' %>

  <% link_to 'Back', inventory_path %>

  </div>
</div>

app/views/inventories/index.html.erb
<div class="row">
  <div class="col-sm-12">

    <ul class="nav nav-pills">
    <li role="presenation"> <%= link_to 'Add New Asset', new_inventory_path %></li>
    <li role="presentation" class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Equipment Type<b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><%= link_to "All", inventories_path %></li>
        <li><%= link_to "Laptops", controller: "inventories", equipment: "Laptop" %></li>
        <li><%= link_to "Desktops", controller: "inventories", equipment: "Desktop" %></li>
        <li><%= link_to "Servers", controller: "inventories", equipment: "Server" %></li>
        <li><%= link_to "Printers", controller: "inventories", equipment: "Printer" %></li>
        <li><%= link_to "Phone", controller: "inventories", equipment: "Phone" %></li>
        <li><%= link_to "Mobile Device", controller: "inventories", equipment: "Mobile Device" %></li>
      </ul>
    </li>
    <li role="presentation" class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Status<b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><%= link_to "All", inventories_path %></li>
        <li><%= link_to "In Use", controller: "inventories", status: "In Use" %></li>
        <li><%= link_to "Spare", controller: "inventories", status: "Spare" %></li>
        <li><%= link_to "In Repair", controller: "inventories", status: "In Repair" %></li>
        <li><%= link_to "Disposed", controller: "inventories", status: "Disposed" %></li>
        <li><%= link_to "Lost", controller: "inventories", status: "Lost" %></li>
        <li><%= link_to "Stolen", controller: "inventories", status: "Stolen" %></li>
      </ul>
    </li>
  </ul>
</div>
</div>

<div class="assets">
  <div class="row">
    <div class="col-sm-12">

      <h1>All Assets:</h1>

      <div class="table-responsive">
        <table class="tablesorter table table-hover" id="show-table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Type</th>
              <th>Model</th>
              <th>Serial</th>
              <th>Owner</th>
              <th>Status</th>
              <th>Edit</th>
              <th>Remove</th>
            </tr>
          </thead>

          <tbody>
            <% @inventory.each do |inventory| %>
            <tr>
              <td><%= link_to inventory.name, inventory_path(inventory) %></td>
              <td><%= inventory.equipment %></td>
              <td><%= inventory.model %></td>
              <td><%= inventory.serial %></td>
              <td><%= inventory.owner %></td>
              <td><%= inventory.status %></td>
              <div class="edit-icon">
                <td><%= link_to '<i class="fa fa-pencil-square-o"></i>'.html_safe, edit_inventory_path(inventory) %></td>
              </div>
              <div class="remove-icon">
                <td><%= link_to '<i class="fa fa-times"></i>'.html_safe, inventory_path(inventory),
                      method: :delete,
                      data: { confirm: 'Are you sure?' } %></td>
              </div>
            </tr>

            <% end %>
          </tbody>

        </table>
      </div>

      <%= will_paginate @inventory, renderer: BootstrapPagination::Rails %>

    </div>
  </div>
</div>

app/views/inventories/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>New Asset</h1>

    <%= render 'layouts/assetform' %>

  </div>
</div>

app/views/inventories/show.html.erb
<div class="record-show">
  <i class="fa fa-arrow-left"></i> <%= link_to 'Back to Assets', inventories_path %>

  <h1>Asset Details</h1>

  <div class="row">
    <div class="col-sm-4">
      <ul>
        <li><strong>Name:</strong> <%= @inventory.name %></li>
        <li><strong>Barcode:</strong> <%= @inventory.barcode %></li>
        <li><strong>Equipment Type:</strong> <%= @inventory.equipment %></li>
        <li><strong>Manufacturer:</strong> <%= @inventory.manufacturer %></li>
        <li><strong>Model:</strong> <%= @inventory.model %></li>
        <li><strong>Serial:</strong> <%= @inventory.serial %></li>
        <li><strong>Service Tag:</strong> <%= @inventory.service_tag %></li>
      </ul>
    </div>

    <div class="col-sm-4">
      <ul>
        <li><strong>Operating System:</strong> <%= @inventory.operating_system %></li>
        <li><strong>IP Address:</strong> <%= @inventory.ip_address %></li>
        <li><strong>Purchase Date:</strong> <%= @inventory.purchasedate %></li>
        <li><strong>Status:</strong> <%= @inventory.status %></li>
        <li><strong>Owner:</strong> <%= @inventory.owner %></li>
        <li><strong>Department:</strong> <%= @inventory.department %></li>
      </ul>
    </div>
</div>

<div class="row">
  <div class="col-sm-6">
    <ul>
      <li><strong>Comments:</strong> <%= @inventory.comments %></li>
    </ul>
  </div>
</div>

</div>

<div class="show-buttons">

  <span><%= link_to 'Edit', edit_inventory_path, class: "btn btn-primary btn-sm" %></span>

  <span><%= link_to 'Delete', inventory_path,
                method: :delete,
                class: "btn btn-primary btn-sm",
                  data: { confirm: 'Are you sure?' } %></span>
</div>