config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  resources :inventories

  resources :contracts

  resources :tickets do
    resources :comments
  end

  get 'dashboard' => 'dashboard#index', as: :dashboard

  get 'search' => 'search#index', as: :search

  get 'signup' => 'users#new'
  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  match "*path", to: "sessions#new", via: :all

end

app/models/contract.rb
class Contract < ActiveRecord::Base

  # Paperclip
  has_attached_file :contract_attach, :default_url => ''
  validates_attachment_content_type :contract_attach, content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif','application/pdf']
  validates_attachment_file_name :contract_attach, :matches => [/png\Z/, /jpe?g\Z/, /pdf\Z/]

  # Filter on contract index.html
  def self.by_type(type)
    if type.present?
      where(contract_type: type)
    else
      all
    end
  end

  # Filter on contract index.html
  def self.by_status(status)
    if status.present?
      where(status: status)
    else
      all
    end
  end

  # Filter on contract index.html
  def self.by_expiration(expiration)
    if expiration.present?
      where("end_date < ?", (Date.today + 60))
    else
      all
    end
  end

end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :logged_in_user

  def new
		@contract = Contract.new
  end

  def create
    @contract = Contract.new(contract_params)

    if @contract.save
      flash[:success] = "Contract successfully created."
    	redirect_to @contract
		else
			render 'new'
		end
  end

  def show
    @contract = Contract.find(params[:id])
  end

  def edit
    @contract = Contract.find(params[:id])
  end

  def update
    @contract = Contract.find(params[:id])

    if @contract.update(contract_params)
      redirect_to @contract
    else
      render 'edit'
    end
  end

  def destroy
    @contract = Contract.find(params[:id])
    @contract.destroy
    flash[:success] = "Contract successfully deleted."
    redirect_to contracts_path
  end

  def destroy_attachment
    @contract.contract_attach = nil
    @contract.save
  end

  def index
    @contracts = Contract.by_type(params[:contract_type]).by_status(params[:status]).paginate(page: params[:page], per_page: 15)
  end

private
  def contract_params
    params.require(:contract).permit(
    :contract_title,
    :contract_number,
    :start_date,
    :end_date,
    :vendor,
    :status,
    :contact,
    :description,
    :po_number,
    :purchase_date,
    :contract_cost,
    :contract_attach,
    :contract_type
    )
  end

end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/views/contracts/edit.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>Edit Contract</h1>

    <%= render 'layouts/contractform' %>

    <% link_to 'Back', inventory_path %>

  </div>
</div>

app/views/contracts/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <ul class="nav nav-pills">
    <li role="presenation"> <%= link_to 'Add New Contract', new_contract_path %></li>
    <li role="presentation" class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Contract Type<b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><%= link_to "All", contracts_path %></li>
        <li><%= link_to "Maintenance", controller: "contracts", contract_type: "Maintenance" %></li>
        <li><%= link_to "Lease", controller: "contracts", contract_type: "Lease" %></li>
        <li><%= link_to "Support", controller: "contracts", contract_type: "Support" %></li>
        <li><%= link_to "Subscription", controller: "contracts", contract_type: "Subscription" %></li>
      </ul>
    </li>
    <li role="presentation" class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Status<b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><%= link_to "All", contracts_path %></li>
        <li><%= link_to "Active", controller: "contracts", status: "Active" %></li>
        <li><%= link_to "Expired", controller: "contracts", status: "Expired" %></li>
        <li><%= link_to "Purchased", controller: "contracts", status: "Purchased" %></li>
      </ul>
    </li>
  </ul>
</div>
</div>


<div class="row">
  <div class="col-sm-12">

    <h1>All Contracts:</h1>
    <div class="table-responsive">
      <table id="show-table" class="tablesorter table table-hover">
        <thead>
        <tr>
          <th>Name</th>
          <th>Agreement Number</th>
          <th>Vendor</th>
          <th>Status</th>
          <th>End Date</th>
          <th>Edit</edit>
          <th>Remove</th>
        </tr>
      </thead>

      <tbody>
        <% @contracts.each do |contract| %>
          <tr>
            <td><%= link_to contract.contract_title, contract_path(contract) %></td>
            <td><%= contract.contract_number %></td>
            <td><%= contract.vendor %></td>
            <td><%= contract.status %></td>
            <td><%= contract.end_date %></td>
            <div class="edit-icon">
              <td><%= link_to '<i class="fa fa-pencil-square-o"></i>'.html_safe, edit_contract_path(contract) %></td>
            </div>
            <td><%= link_to '<i class="fa fa-times"></i>'.html_safe, contract_path(contract),
                              method: :delete,
                              data: { confirm: 'Are you sure?' } %></td>
          </tr>
            <% end %>
          </tbody>

        </table>
      </div>

      <%= will_paginate @contract, renderer: BootstrapPagination::Rails %>

    </div>
</div>

app/views/contracts/new.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>New Contract</h1>

    <%= render 'layouts/contractform' %>

  </div>
</div>

app/views/contracts/show.html.erb
<div class="record-show">
  <i class="fa fa-arrow-left"></i> <%= link_to 'Back to Contracts', contracts_path %>

  <h1>Contract Details</h1>

  <div class="row">
    <div class="col-sm-4">
      <ul>
        <li><strong>Name:</strong> <%= @contract.contract_title %></li>
        <li><strong>Agreement Number:</strong> <%= @contract.contract_number %></li>
        <li><strong>Vendor:</strong> <%= @contract.vendor %></li>
        <li><strong>Contact:</strong> <%= @contract.contact %></li>
        <li><strong>Start Date:</strong> <%= @contract.start_date %></li>
        <li><strong>End Date:</strong> <%= @contract.end_date%></li>
      </ul>
    </div>

    <div class="col-sm-4">
      <ul>
        <li><strong>PO Number:</strong> <%= @contract.po_number %></li>
        <li><strong>Purchase Date:</strong> <%= @contract.purchase_date %></li>
        <li><strong>Cost:</strong> <%= @contract.contract_cost %></li>
        <li><strong>Status:</strong> <%= @contract.status %></li>
        <li><strong>Type:</strong> <%= @contract.contract_type %></li>
        <li><strong>Attachment:</strong> <%= link_to @contract.contract_attach_file_name, @contract.contract_attach.url %></li>
      </ul>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <ul>
        <li><strong>Description:</strong> <%= @contract.description %></li>
      </ul>
    </div>
  </div>
</div>

<div class="show-buttons">

    <span><%= link_to 'Edit', edit_contract_path, class: "btn btn-primary btn-sm" %></span>

    <span><%= link_to 'Delete', contract_path,
              method: :delete,
              data: { confirm: 'Are you sure?' }, class: "btn btn-primary btn-sm" %></span>
</div>