config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  resources :inventories

  resources :contracts

  resources :tickets do
    resources :comments
  end

  get 'dashboard' => 'dashboard#index', as: :dashboard

  get 'search' => 'search#index', as: :search

  get 'signup' => 'users#new'
  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  match "*path", to: "sessions#new", via: :all

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :comments

  before_save { self.email = email.downcase }
  validates :first_name,  presence: true, length: { maximum: 50 }
  validates :last_name,  presence: true, length: { maximum: 50 }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  #bcrypt
  has_secure_password

  # User role
  def user?
  	self.role == 'user'
	end

  # Admin role
  def admin?
  	self.role == 'admin'
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user, only: [:edit, :update]
  before_action :require_admin, only: [:new, :create, :index, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Account created successfully."
      redirect_to users_path
    else
      flash[:alert] = "Bad combination. Please try again."
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "User deleted"
    redirect_to users_path
  end

  def index
    @users = User.all
  end

  private
  def user_params
    params.require(:user).permit(
    :first_name,
    :last_name,
    :email,
    :password,
    :password_confirmation,
    :role
    )
  end

  # Admin role allowance/block.
  def require_admin
    redirect_to root_url unless current_user.admin?
  end

  # Only a user can edit their profile or admin can edit any profile.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user || current_user.admin?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

<div class="row">
  <div class="col-md-5 col-md-offset-3">

    <%= form_for(@user) do |f| %>

      <h1>Update profile</h1>

      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: 'form-control' %>

      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label "Password Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <% if current_user && current_user.admin? %>

        <%= f.label :role %>
        <%= f.select(:role, ['user','admin'], {}, { class: 'form-control' }) %>

      <% end %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>

  <div class="row">
    <div class="col-sm-12">

      <%= link_to "Add New User", new_user_path, class: "btn btn-primary btn-sm" %>

      <h1>All Users:</h1>
      <div class="table-responsive">
        <table class="tablesorter table table-hover" id="show-table">
          <thead>
            <tr>
              <th>First Name</th>
              <th>Last Name</th>
              <th>Email</th>
              <th>Role</th>
              <th>Edit</edit>
              <th>Delete</th>
            </tr>
          </thead>

          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td><%= user.first_name %></td>
              <td><%= user.last_name %></td>
              <td><%= user.email %></td>
              <td><%= user.role %></td>
              <div class="edit-icon">
                <td><%= link_to '<i class="fa fa-pencil-square-o"></i>'.html_safe, edit_user_path(user) %></td>
              </div>
              <td><%= link_to '<i class="fa fa-times"></i>'.html_safe, user_path(user),
                                method: :delete,
                                data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
          </tbody>

        </table>
      </div>


    </div>
  </div>

app/views/users/new.html.erb
<% provide(:title, "New user") %>

<div class="signup-form">

  <div class="row">
    <div class="form-group col-sm-4 col-sm-offset-4">

      <%= form_for @user do |f| %>

      <h1>Sign Up:</h1>

      <%= f.label "First Name" %>
      <%= f.text_field :first_name, class: 'form-control' %>

      <%= f.label "Last Name" %>
      <%= f.text_field :last_name, class: 'form-control' %>

      <%= f.label "Email" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label "Password" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label "Password Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.label :role %>
      <%= f.select(:role, ['user','admin'], {}, { class: 'form-control' }) %>

      <%= f.submit "Submit", class: "btn btn-primary btn-sm" %>

      <% end %>

    </div>
  </div>
</div>