config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  resources :inventories

  resources :contracts

  resources :tickets do
    resources :comments
  end

  get 'dashboard' => 'dashboard#index', as: :dashboard

  get 'search' => 'search#index', as: :search

  get 'signup' => 'users#new'
  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  match "*path", to: "sessions#new", via: :all

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :ticket
  belongs_to :user
end

app/models/contract.rb
class Contract < ActiveRecord::Base

  # Paperclip
  has_attached_file :contract_attach, :default_url => ''
  validates_attachment_content_type :contract_attach, content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif','application/pdf']
  validates_attachment_file_name :contract_attach, :matches => [/png\Z/, /jpe?g\Z/, /pdf\Z/]

  # Filter on contract index.html
  def self.by_type(type)
    if type.present?
      where(contract_type: type)
    else
      all
    end
  end

  # Filter on contract index.html
  def self.by_status(status)
    if status.present?
      where(status: status)
    else
      all
    end
  end

  # Filter on contract index.html
  def self.by_expiration(expiration)
    if expiration.present?
      where("end_date < ?", (Date.today + 60))
    else
      all
    end
  end

end

app/models/inventory.rb
class Inventory < ActiveRecord::Base
  
  # scope :by_name, -> name { where(name: name) if status.present? }

  # Filter on inventories index.html
  def self.by_equipment(equipment)
    if equipment.present?
      where(equipment: equipment)
    else
      all
    end
  end

  # Filter on inventories index.html
  def self.by_status(status)
    if status.present?
      where(status: status)
    else
      all
    end
  end

end

app/models/search.rb
class Search
  def self.for(keyword)
    Inventory.where("name LIKE ?", "%#{keyword.downcase}%") +
    Inventory.where("owner LIKE ?", "%#{keyword.downcase}%") +
    Contract.where("contract_number LIKE ?", "%#{keyword.downcase}%")
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base

  has_many :comments

  # Paperclip
  has_attached_file :attachment, :default_url => ''
  validates_attachment_content_type :attachment, content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif','application/pdf']
  validates_attachment_file_name :attachment, :matches => [/png\Z/, /jpe?g\Z/, /pdf\Z/]

  # Filter on ticket index.html
  def self.by_severity(severity)
    if severity.present?
      where(severity: severity)
    else
      all
    end
  end

  # Filter on ticket index.html
  def self.by_status(status)
    if status.present?
      where(status: status)
    else
      all
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :comments

  before_save { self.email = email.downcase }
  validates :first_name,  presence: true, length: { maximum: 50 }
  validates :last_name,  presence: true, length: { maximum: 50 }
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  #bcrypt
  has_secure_password

  # User role
  def user?
  	self.role == 'user'
	end

  # Admin role
  def admin?
  	self.role == 'admin'
	end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @ticket = Ticket.find(params[:ticket_id])
    @comment = @ticket.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
    redirect_to ticket_path(@ticket)
  end

  private
    def comment_params
      params.require(:comment).permit(:body,:user)
    end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :logged_in_user

  def index
    if jump = jump_target
      redirect_to jump
    else
      @results = Search.for(params[:keyword])
    end
  end

  private
    def jump_target
      Inventory.find_by(name: params[:keyword]) ||
      Contract.find_by(contract_number: params[:keyword])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  #before_filter :logged_in_user

  layout 'login'

  def new
  end

  def create
    @user = User.find_by_email(params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to login_path
      flash[:error] = "Bad username or password."
    end
	end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :logged_in_user

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)

    if @ticket.save
      flash[:success] = "Ticket successfully created."
      redirect_to @ticket
    else
      render 'new'
    end
  end

  def show
    @ticket = Ticket.find(params[:id])
  end

  def edit
    @ticket = Ticket.find(params[:id])
  end

  def update
    @ticket = Ticket.find(params[:id])

    if @ticket.update(ticket_params)
      redirect_to @ticket
    else
      render 'edit'
    end
  end

  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy
    flash[:success] = "Ticket successfully deleted."
    redirect_to tickets_path
  end

  def index
    @tickets = Ticket.by_severity(params[:severity]).by_status(params[:status]).paginate(page: params[:page], per_page: 15)
  end

  private
    def ticket_params
      params.require(:ticket).permit(
      :contact,
      :severity,
      :assigned,
      :summary,
      :description,
      :status,
      :attachment
      )
    end

  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user, only: [:edit, :update]
  before_action :require_admin, only: [:new, :create, :index, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Account created successfully."
      redirect_to users_path
    else
      flash[:alert] = "Bad combination. Please try again."
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Profile updated"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "User deleted"
    redirect_to users_path
  end

  def index
    @users = User.all
  end

  private
  def user_params
    params.require(:user).permit(
    :first_name,
    :last_name,
    :email,
    :password,
    :password_confirmation,
    :role
    )
  end

  # Admin role allowance/block.
  def require_admin
    redirect_to root_url unless current_user.admin?
  end

  # Only a user can edit their profile or admin can edit any profile.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user || current_user.admin?
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Provides full title for each page_title
  def full_title(page_title = '')
    base_title = "AssetWire"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

  def available_at
    return super.to_datetime if super.respond_to?(:to_datetime)
    DateTime.parse(super)
  end

  # Bootstrap alert messages. Called in /shared/_alerts.html.erb
  def bootstrap_class_for(flash_type)
      case flash_type
        when "success"
          "alert-success"   # Green
        when "error"
          "alert-danger"    # Red
        when "alert"
          "alert-warning"   # Yellow
        when "notice"
          "alert-info"      # Blue
        else
          flash_type.to_s
      end
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_assetform.html.erb
<%= form_for @inventory do |f| %>
<div class="row">
  <div class="form-group col-sm-3">

    <%= f.label "Asset Name" %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :barcode %>
    <%= f.text_field :barcode, class: 'form-control' %>

    <%= f.label :serial %>
    <%= f.text_field :serial, class: 'form-control' %>

    <%= f.label "Service Tag" %>
    <%= f.text_field :service_tag, class: 'form-control' %>

    <%= f.label "Equipment Type" %>
    <%= f.select(:equipment, ['Laptop', 'Desktop', 'Phone', 'Mobile Device' 'Server', 'Switch', 'Router', 'Wireless AP'], {}, { class: 'form-control' }) %>

  </div>

  <div class="form-group col-sm-3">

    <%= f.label :manufacturer %>
    <%= f.text_field :manufacturer, class: 'form-control' %>

    <%= f.label :model %>
    <%= f.text_field :model, class: 'form-control' %>

    <%= f.label :owner %>
    <%= f.text_field :owner, class: 'form-control' %>

    <%= f.label :department %>
    <%= f.text_field :department, class: 'form-control' %>

    <%= f.label :status %>
    <%= f.select(:status, ['In Use', 'Spare', 'Disposed', 'In Repair', 'Lost', 'Stolen'], {}, { class: 'form-control' }) %>

  </div>

  <div class="form-group col-sm-3">

    <%= f.label "Purchase Date" %>
    <%= f.date_field :purchasedate, class: 'form-control' %>

    <%= f.label "IP Address" %>
    <%= f.text_field :ip_address, class: 'form-control' %>

    <%= f.label "Operating System" %>
    <%= f.select(:operating_system, ['Windows XP','Windows 7','Windows 8/8.1','Windows 10','Windows 2003','Windows 2008','Windows 2012'], {}, { class: 'form-control'}) %>

  </div>

</div>

<div class="row">
  <div class="form-group col-sm-6">
    <%= f.label :comments %>
    <%= f.text_area :comments, class: 'form-control' %>

    <%= f.submit "Submit", class: "btn btn-primary btn-sm" %>

  </div>
</div>

<% end %>

app/views/layouts/_commentform.html.erb
<%= form_for([@ticket, @ticket.comments.build]) do |f| %>
<div class="row">
  <div class="form-group col-sm-6">
    <%= f.label "Log Entry" %>
    <%= f.text_area :body, class: 'form-control' %>

    <%= f.submit "Submit", class: "btn btn-primary btn-sm" %>
  </div>
</div>
<% end %>

<p>Work Log:</p>
<% @ticket.comments.each do |comment| %>
<% if comment.user != nil %>
<p>Posted on
  <%= comment.created_at.strftime('%b %e, %l:%M %p') %>
  by:
  <%= comment.user.first_name %>
  <%= comment.user.last_name %></p>
<% end %>
<p><%= comment.body %></p>
<% end %>

app/views/layouts/_contractform.html.erb
<%= form_for @contract, html: { multipart: true } do |f| %>
<div class="row">
  <div class="form-group col-sm-3">

    <%= f.label "Name" %>
    <%= f.text_field :contract_title, class: 'form-control' %>

    <%= f.label "Agreement Number" %>
    <%= f.text_field :contract_number, class: 'form-control' %>

    <%= f.label "Vendor" %>
    <%= f.text_field :vendor, class: 'form-control' %>

    <%= f.label "Contact" %>
    <%= f.text_field :contact, class: 'form-control' %>

  </div>

  <div class="form-group col-sm-3">

    <%= f.label "PO Number" %>
    <%= f.text_field :po_number, class: 'form-control' %>

    <%= f.label "Purchase Date" %>
    <%= f.date_field :purchase_date, class: 'form-control' %>

    <%= f.label "Cost" %>
    <%= f.text_field :contract_cost, class: 'form-control' %>

    <%= f.label :contract_type %>
    <%= f.select(:contract_type, ['Maintenance', 'Lease', 'Support', 'Subscription'], {}, { class: 'form-control' }) %>

  </div>

  <div class="form-group col-sm-3">
    <%= f.label "Start Date" %>
    <%= f.date_field :start_date, :default=>Date.today.strftime("%d/%m/%Y"), class: 'form-control' %>

    <%= f.label "End Date" %>
    <%= f.date_field :end_date, class: 'form-control' %>

    <%= f.label :status %>
    <%= f.select(:status, ['Active', 'Expired', 'Purchased'], {}, { class: 'form-control'}) %>

  </div>

</div>
<!-- Row end -->

<div class="row">
  <div class="form-group col-sm-6">
    <%= f.label "Attachment" %>
    <%= f.file_field :contract_attach %><br>
    <% if @contract.contract_attach.file? %>
    <p>Attached:</p>
    <p><%= link_to @contract.contract_attach_file_name, @contract.contract_attach.url %></p>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="form-group col-sm-6">
    <%= f.label "Description" %>
    <%= f.text_area :description, class: 'form-control' %>

    <%= f.submit "Submit", class: "btn btn-primary btn-sm"%>
  </div>
</div>

<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "AssetWire", root_path, class: "navbar-brand" %>
            </div>
            <!-- /.navbar-header -->
            <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-top-links navbar-right">
                <% if logged_in? %>
                    <li><%= current_user.first_name %> <%= current_user.last_name %></li>
                    <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><%= link_to '<i class="fa fa-user fa-fw"></i> User Profile'.html_safe, edit_user_path(current_user) %></li>

                        <% if current_user && current_user.admin? %>
                                <li><%= link_to '<i class="fa fa-cogs"></i> Admin Panel'.html_safe, users_path %></li>
                        <% end %>

                        <li class="divider"></li>
                        <li><%= link_to '<i class="fa fa-sign-out fa-fw"></i> Logout'.html_safe, logout_path, method: "delete" %></li>
                    </ul>
                </li><!-- /.dropdown-user -->
                <% else %>
                        <li><%= link_to "Login", 'login' %></li>
                <% end %>
                <!-- /.dropdown -->
            </ul>
    </div>
            <!-- /.navbar-top-links -->

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <%= form_tag search_path, class: 'form-inline', method: :get do %>
                            <%= text_field_tag 'keyword', nil, class: 'form-control' %>
                            <%= button_tag '<i class="fa fa-search"></i>'.html_safe, class: 'btn btn-default', :name => nil %>
                            <% end %>
                        </li>
                        <li><%= link_to '<i class="fa fa-dashboard fa-fw"></i> Dashboard'.html_safe, root_path %></li>
                        <li><%= link_to '<i class="fa fa-desktop fa-fw"></i> View Assets'.html_safe, inventories_path %></li>
                        <li><%= link_to '<i class="fa fa-pencil-square-o fa-fw"></i> View Contracts'.html_safe, contracts_path %></li>
                        <li><%= link_to '<i class="fa fa-life-ring fa-fw"></i> View Tickets'.html_safe, tickets_path %></li>
                        <div class="quick-links-menu">
                                <span><li>Quick Links</li></span>
                                        <ul class="nav">
                                                <li><%= link_to '<i class="fa fa-angle-double-right fa-fw"></i> New Ticket'.html_safe, new_ticket_path %></li>
                                                <li><%= link_to '<i class="fa fa-angle-double-right fa-fw"></i> New Asset'.html_safe, new_inventory_path %></li>
                                                <li><%= link_to '<i class="fa fa-angle-double-right fa-fw"></i> New Contract'.html_safe, new_contract_path %></li>
                                        </ul>
                        </div>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

app/views/layouts/_ticketform.html.erb
<%= form_for @ticket do |f| %>
<div class="row">
  <div class="form-group col-md-3">

    <%= f.label "Contact" %>
    <%= f.text_field :contact, class: 'form-control' %>

    <%= f.label :severity %>
    <%= f.select(:severity, ['Low','Medium','High'], {}, { class: 'form-control' }) %>

    <%= f.label "Summary" %>
    <%= f.text_field :summary, class: 'form-control' %>

  </div>

    <div class="col-md-3">

    <%= f.label :assigned %>
    <%= f.select(:assigned, ['George Anderson','Stefani Irma','Peyton Conor'], {}, { class: 'form-control' }) %>

    <%= f.label :status %>
    <%= f.select(:status, ['Working','Pending On Customer','Pending on Vendor','On Hold','In Queue'], {}, { class: 'form-control' }) %>

    <%= f.label "Attachment" %>
    <%= f.file_field :attachment %><br>
    <% if @ticket.attachment.file? %>
      <p>Attached:</p>
      <p><%= link_to @ticket.attachment_file_name, @ticket.attachment.url %></p>
    <% end %>

  </div>
</div>

  <div class="row">
    <div class="col-sm-7">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>

    <%= f.submit "Submit", class: "btn btn-primary btn-sm" %>

  </div>
</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= full_title(yield(:title)) %></title>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

  <%= csrf_meta_tags %>
</head>
<body>

<div id="wrapper">

  <%= render 'layouts/navbar' %>

       <div id="page-wrapper">
           <div class="container-fluid">
               <div class="row">
                   <div class="col-lg-12">
                        <div id="page-header">

                          <%= render 'shared/alerts' %>

                          <%= yield %>

                       </div>
                   </div>
               </div>
           </div>
      </div>
</div>

</body>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

<script>
$(document).ready(function()
    {
        $("#show-table").tablesorter();
    }
);
</script>

</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <title><%= full_title(yield(:title)) %></title>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">

    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">


    <%= render 'shared/alerts' %>

    <%= yield %>

</div>

  </body>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <script>
$(document).ready(function () {
  $("#show-table").tablesorter();
});
  </script>

</html>

app/views/shared/_alerts.html.erb
<!-- Rendered in application_layout -->

<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %>" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= message %>
  </div>
<% end %>